name: sqflite_generator
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen:
  analyzer:
  sqflite:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  build:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

builders:
  sqliteHelperBuilder:
    import: "package:sqflite_generator/builder.dart"
    builder_factories: ["sqliteHelperBuilder"]
    build_extensions: {".dart": [".sqlite_helper.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]